[project]
name = "bomberman"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alii-Khaled", email = "alii.khaled97@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4",
    "pygame>=2.6",
    "tqdm>=4.70",
    "matplotlib>=3.10",
    "torch>=2.5",
    "torchvision>=0.20",
]

[project.scripts]
bomberman = "bomberman:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
